// src/lib/components/TimePicker.svelte
<script lang="ts">
	import { ChevronUp, ChevronDown } from '@lucide/svelte';

	interface Props {
		value?: string;
		onChange?: (time: string) => void;
		large?: boolean;
	}

	let { value = '', onChange, large = false }: Props = $props();

	type Period = 'AM' | 'PM';

	let hour = $state('');
	let minute = $state('');
	let period = $state<Period>('AM');

	$effect(() => {
		const m = value.match(/^(\d{1,2}):(\d{1,2}) (AM|PM)$/);
		if (m) {
			hour = m[1];
			minute = m[2];
			period = m[3] as Period;
		}
	});

	function emit() {
		onChange?.(`${hour.padStart(2, '0')}:${minute.padStart(2, '0')} ${period}`);
	}

	function bumpHour(dir: number) {
		const cur = parseInt(hour, 10) || 0;
		const n = dir > 0 ? (cur >= 12 ? 1 : cur + 1) : cur <= 1 ? 12 : cur - 1;
		hour = String(n);
		emit();
	}

	function bumpMinute(dir: number) {
		const cur = parseInt(minute, 10) || 0;
		minute = dir > 0 ? (cur >= 59 ? '00' : String(cur + 1)) : cur <= 0 ? '59' : String(cur - 1);
		emit();
	}

	function togglePeriod() {
		period = period === 'AM' ? 'PM' : 'AM';
		emit();
	}
</script>

<div class="flex items-center {large ? 'gap-1.5' : 'gap-1'}">
	<div class="flex flex-col items-center">
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={() => bumpHour(1)}>
			<ChevronUp class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
		<input
			type="text"
			placeholder="__"
			maxlength="2"
			bind:value={hour}
			oninput={emit}
			class="focus:border-[#DDBB5E] focus:ring-1 focus:ring-[#DDBB5E] flex items-center justify-center rounded-md border border-input bg-transparent text-center tabular-nums text-white/90 {large ? 'size-12 text-base rounded-lg' : 'size-10 text-sm'}"
		/>
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={() => bumpHour(-1)}>
			<ChevronDown class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
	</div>
	<span class="text-white/90 {large ? 'text-xl' : 'text-lg'}">:</span>
	<div class="flex flex-col items-center">
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={() => bumpMinute(1)}>
			<ChevronUp class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
		<input
			type="text"
			placeholder="__"
			maxlength="2"
			bind:value={minute}
			oninput={emit}
			class="focus:border-[#DDBB5E] focus:ring-1 focus:ring-[#DDBB5E] flex items-center justify-center rounded-md border border-input bg-transparent text-center tabular-nums text-white/90 {large ? 'size-12 text-base rounded-lg' : 'size-10 text-sm'}"
		/>
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={() => bumpMinute(-1)}>
			<ChevronDown class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
	</div>
	<div class="flex flex-col items-center">
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={togglePeriod}>
			<ChevronUp class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
		<button
			type="button"
			class="focus:border-[#DDBB5E] focus:ring-1 focus:ring-[#DDBB5E] flex items-center justify-center rounded-md border border-input bg-transparent text-center tabular-nums text-white/90 cursor-pointer hover:border-[#DDBB5E] {large ? 'size-12 text-base rounded-lg' : 'size-10 text-sm'}"
			onclick={togglePeriod}
		>
			{period}
		</button>
		<button type="button" class="flex {large ? 'h-6' : 'h-5'} items-center justify-center cursor-pointer" onclick={togglePeriod}>
			<ChevronDown class="text-[var(--gold-accent)] {large ? 'size-4' : 'size-3'}" />
		</button>
	</div>
</div>

// src/components/ui/time-picker.tsx
"use client"

import * as React from "react"
import { ChevronUpIcon, ChevronDownIcon } from "lucide-react"
import { cn } from "@/lib/utils"

type Period = "AM" | "PM"

interface TimePickerContextProps {
  setRef: (type: "hour" | "minute" | "period", element: HTMLInputElement | null) => void
  onUpChange?: (type: "hour" | "minute" | "period") => void
  onLeftChange?: (type: "hour" | "minute" | "period") => void
}

const TimePickerContext = React.createContext<TimePickerContextProps | null>(null)

function useTimePickerContext() {
  const context = React.useContext(TimePickerContext)
  if (!context) {
    throw new Error("TimePicker components must be used within <TimePicker>")
  }
  return context
}

interface TimePickerInputProps extends Omit<React.ComponentProps<"input">, "onChange"> {
  onUpChange?: () => void
  onLeftChange?: () => void
  onChange?: (value: string | number) => void
  type?: "hour" | "minute" | "period"
  maxLength?: number
}

function TimePickerInput({
  className,
  type = "hour",
  maxLength = 2,
  placeholder = "__",
  onUpChange,
  onLeftChange,
  onChange,
  ...props
}: TimePickerInputProps) {
  const [isFocused, setIsFocused] = React.useState(false)
  const [showOverlay, setShowOverlay] = React.useState(false)
  const inputRef = React.useRef<HTMLInputElement | null>(null)
  const { setRef } = useTimePickerContext()

  React.useEffect(() => {
    setRef(type, inputRef.current)
  }, [setRef, type])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowUp") {
      onUpChange?.()
    } else if (e.key === "ArrowLeft") {
      onLeftChange?.()
    }
  }

  return (
    <div className="flex flex-col items-center">
      <button
        type="button"
        className="flex h-5 items-center justify-center"
        onClick={onUpChange}
      >
        <ChevronUpIcon className="size-3 text-[var(--gold-accent)]" />
      </button>
      <input
        ref={inputRef}
        type="text"
        placeholder={placeholder}
        className={cn(
          "flex size-10 items-center justify-center rounded-md border border-input bg-transparent text-center tabular-nums text-white/90 font-[arial]",
          isFocused && "border-[#DDBB5E] ring-1 ring-[#DDBB5E]",
          className
        )}
        maxLength={maxLength}
        onFocus={() => setIsFocused(true)}
        onBlur={() => setIsFocused(false)}
        onKeyDown={handleKeyDown}
        {...props}
      />
      <button
        type="button"
        className="flex h-5 items-center justify-center"
        onClick={() => onLeftChange?.()}
      >
        <ChevronDownIcon className="size-3 text-[var(--gold-accent)]" />
      </button>
    </div>
  )
}

interface TimePickerProps {
  value?: string
  onChange?: (time: string) => void
  className?: string
}

function TimePicker({ value, onChange, className }: TimePickerProps) {
  const [period, setPeriod] = React.useState<Period>("AM")
  const hourRef = React.useRef<HTMLInputElement | null>(null)
  const minuteRef = React.useRef<HTMLInputElement | null>(null)
  const periodRef = React.useRef<HTMLInputElement | null>(null)

  const setRef = React.useCallback((type: "hour" | "minute" | "period", element: HTMLInputElement | null) => {
    if (type === "hour") hourRef.current = element
    else if (type === "minute") minuteRef.current = element
    else periodRef.current = element
  }, [])

  const minuteChange = (amount: number) => {
    if (!minuteRef.current) return
    const current = parseInt(minuteRef.current.value, 10) || 0
    const newValue = current + amount
    if (newValue > 59) minuteRef.current.value = "00"
    else if (newValue < 0) minuteRef.current.value = "59"
    else minuteRef.current.value = String(newValue).padStart(2, "0")
  }

  const hourChange = (amount: number) => {
    if (!hourRef.current) return
    const current = parseInt(hourRef.current.value, 10) || 0
    const newValue = current + amount
    if (newValue > 12) hourRef.current.value = "01"
    else if (newValue < 1) hourRef.current.value = "12"
    else hourRef.current.value = String(newValue).padStart(2, "0")
  }

  const periodChange = () => {
    setPeriod((prev) => (prev === "AM" ? "PM" : "AM"))
  }

  const emitChange = React.useCallback(() => {
    if (!hourRef.current || !minuteRef.current) return
    const h = hourRef.current.value.padStart(2, "0")
    const m = minuteRef.current.value.padStart(2, "0")
    onChange?.(`${h}:${m} ${period}`)
  }, [onChange, period])

  return (
    <TimePickerContext.Provider value={{ setRef }}>
      <div className={cn("flex items-center gap-1", className)}>
        <TimePickerInput
          type="hour"
          placeholder="__"
          maxLength={2}
          onUpChange={() => { hourChange(1); emitChange() }}
          onLeftChange={() => { hourChange(-1); emitChange() }}
          onChange={emitChange}
        />
        <span className="text-white/90 text-lg font-[arial]">:</span>
        <TimePickerInput
          type="minute"
          placeholder="__"
          maxLength={2}
          onUpChange={() => { minuteChange(1); emitChange() }}
          onLeftChange={() => { minuteChange(-1); emitChange() }}
          onChange={emitChange}
        />
        <TimePickerInput
          type="period"
          placeholder={period}
          maxLength={2}
          value={period}
          onUpChange={() => { periodChange(); emitChange() }}
          onLeftChange={() => { periodChange(); emitChange() }}
          onChange={emitChange}
        />
      </div>
    </TimePickerContext.Provider>
  )
}

export { TimePicker, TimePickerInput }
